#!/bin/sh


# repository gone MIA
excluded="meta-eca"
# integration of other layers from elsewhere only, ala poky
excluded="$excluded|eldk"
# bits on git.oe.org which aren't metadata-related
excluded="$excluded|oetest|oebuildstats|eclipsetools|openembedded-web-frontpages|openembedded-admin"


canonical_url () {
    # Give us the url in its canonical form
    sed -e '
s,^git://github.com,https://github.com,;
s,^http://github.com,https://github.com,;
s,^git://openembedded\.org,git://git.openembedded.org,;
s,^http://git\.sv\.gnu\.org/,http://git.savannah.gnu.org/,;
s,^git://git\.sv\.gnu\.org/,http://git.savannah.gnu.org/r/,;
s,^git://git\.savannah\.gnu\.org/,http://git.savannah.gnu.org/r/,;
s,\.sf\.net/,.sourceforge.net/,;
s,^git://[^.]\+\.git\.sourceforge\.net/,git://gitscm.sourceforge.net/,;
/git:\/\/gitscm.sourceforge.net\//q;
s,\.git/*$,,;
s,$,.git,;

s,git://git.openembedded.org/openembedded-core.git,https://github.com/openembedded/openembedded-core.git,;
s,git://git.openembedded.org/meta-openembedded.git,https://github.com/openembedded/meta-openembedded.git,;
        '
}

list_urls () {
    curl -s http://layers.openembedded.org/layerindex/branch/master/layers/ | sed -n '/showRollie/{n; s/^ *//; p}'
    curl -s http://git.yoctoproject.org/|sed -n "s#.*href='/cgit/cgit.cgi/\(meta-[^/]*\).*#\1#p" | grep -v '\-contrib' | sed 's#^\(.*\)$#git://git.yoctoproject.org/\1.git#'
    curl -s 'http://git.openembedded.org/'|sed -n "s#.* class='toplevel-repo'><a title='[^']*' href='/\([^']*\)/'.*#git://git.openembedded.org/\1.git#p"

    if [ -x ./extra_layer_urls ]; then
        ./extra_layer_urls
    fi
}

exclude_urls () {
    if [ -n "$excluded" ]; then
        grep -Ev "/($excluded)\.git\$"
    else
        cat
    fi
}

list_urls | canonical_url | exclude_urls | sort -u
