#!/bin/sh -e

if [ $# -eq 0 ]; then
    scriptdir=$(cd $(dirname $0) && pwd)
    for git_dir in $scriptdir/*/.git/; do
        set -- "$@" "${git_dir%.git/}"
    done
fi

for repo; do
    cd "$repo"
    if [ "$(git rev-list ORIG_HEAD..|wc -l)" -gt 0 ]; then
        echo "$(basename "$repo"):"
        git log ORIG_HEAD.. | git shortlog | sed 's,^,  ,'
    fi
    cd - >/dev/null
done
