#!/bin/sh -e

if [ $# -gt 0 ] && [ "$1" == "--rebase" ]; then
    rebase=1
    shift
else
    rebase=0
fi

if [ $# -eq 0 ]; then
    scriptdir=$(cd $(dirname $0) && pwd)
    for git_dir in $scriptdir/*/.git/; do
        set -- "$@" "${git_dir%.git/}"
    done
fi

failed=""
for repo; do
    echo "Updating $repo.."
    cd "$repo"
    git checkout master || failed="$failed $repo"
    if [ "$rebase" -eq 1 ]; then
        git pull --rebase || failed="$failed $repo"
    else
        git pull --ff || failed="$failed $repo"
    fi
    cd - >/dev/null
done

$(dirname $0)/show_updates

if [ -n "$failed" ]; then
    echo >&2 "Warning: updates of these layers failed: $failed"
fi
