#!/bin/sh -e

if [ $# -eq 0 ]; then
    scriptdir=$(cd $(dirname $0) && pwd)
    for git_dir in $scriptdir/*/.git/; do
        set -- "$@" "${git_dir%.git/}"
    done
fi

failed=""
for repo; do
    echo "Updating $repo.."
    cd "$repo"
    git fetch || failed="$failed $repo"
    git merge --ff origin/master || failed="$failed $repo"
    cd - >/dev/null
done

$(dirname $0)/show_updates

if [ -n "$failed" ]; then
    echo >&2 "Warning: updates of these layers failed: $failed"
fi
